services:
  web:
    build:
      context: client
    ports:
      - 5172:5172
    depends_on:
      - api
    environment:
      - APP_PORT=5172
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    build:
      context: server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: ${DB_NAME:-docker}
      DATABASE_USERNAME: ${DB_USERNAME:-docker}
      DATABASE_PASSWORD: ${DB_PASSWORD:-1234}
      DATABASE_URL: ${DATABASE_URL:-postgresql://docker:1234@db:5432/docker}
      DATABASE_PORT: ${DATABASE_PORT:-5433}
    env_file:
      - server/.env

  db:
    image: postgres:14
    build: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-docker}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-docker}
    ports:
      - "5433:5432"
    env_file:
      - server/.env

volumes:
  postgres_data:
