name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run ESLint on ${{ matrix.bundle }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        bundle: [ "server", "client" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies and plugins
        working-directory: ${{ matrix.bundle }}
        run: |
          # Install project dependencies
          if [[ -f package-lock.json ]]; then
            npm ci
          else
            npm install
          fi

          # Ensure required ESLint plugins are present
          npm install --save-dev \
            eslint \
            @typescript-eslint/eslint-plugin \
            @typescript-eslint/parser \
            eslint-plugin-react \
            eslint-plugin-react-hooks \
            eslint-plugin-react-refresh

      - name: Run ESLint
        working-directory: ${{ matrix.bundle }}
        id: lint
        continue-on-error: true
        run: |
          OUTPUT_FILE="${RUNNER_TEMP}/eslint_output.txt"
          
          # Run eslint and output results
          if ! npx eslint . -f stylish > "$OUTPUT_FILE" 2>&1; then
            echo "failed=true" >> $GITHUB_OUTPUT
          else
            echo "failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Report Lint Results
        run: |
          OUTPUT_FILE="${RUNNER_TEMP}/eslint_output.txt"

          if [[ "${{ steps.lint.outputs.failed }}" == "true" ]]; then
            echo "# ❌ Lint failed in ${{ matrix.bundle }}" >> $GITHUB_STEP_SUMMARY
            if [[ -f "$OUTPUT_FILE" ]]; then
              echo "## ESLint Output:" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              cat "$OUTPUT_FILE" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "---- Console ESLint Output ----"
              cat "$OUTPUT_FILE"
              echo "--------------------------------"
            fi
            exit 1
          else
            echo "# ✅ Lint passed for ${{ matrix.bundle }}" >> $GITHUB_STEP_SUMMARY
            echo "No lint issues found :rocket:" >> $GITHUB_STEP_SUMMARY
          fi
