name: Unit Tests - Server

on:
  pull_request:
    branches:
      - main
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Run tests
        run: |
          pytest server/tests/unit_tests/user_tests_UT.py
          echo "__test passed!__ ✅" >> $GITHUB_STEP_SUMMARY